src/objects/Change__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Environment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>Changes</relationshipLabel>
        <relationshipName>Changes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manual_Change__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Manual Change</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Metadata__c</fullName>
        <label>Metadata</label>
        <picklist>
            <picklistValues>
                <fullName>Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Object</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Page Layout</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Picklist Values</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Profile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Role Hierarchy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trigger</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VF Page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Workflow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Story_ID__c</fullName>
        <label>Story ID</label>
        <length>63</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Create</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Change</label>
    <nameField>
        <displayFormat>MC-{00000}</displayFormat>
        <label>Change Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Changes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Change_Junction__c.object
<CustomObject>
    <fields>
        <fullName>Change_Set__c</fullName>
        <label>Change Set</label>
        <referenceTo>Change_Set__c</referenceTo>
        <relationshipLabel>Changes</relationshipLabel>
        <relationshipName>Change_Junctions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Change__c</fullName>
        <label>Change</label>
        <referenceTo>Change__c</referenceTo>
        <relationshipLabel>Change Sets</relationshipLabel>
        <relationshipName>Change_Junctions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Change Junction</label>
    <nameField>
        <displayFormat>MCJ-{00000}</displayFormat>
        <label>Change Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Change_Set__c.object
<CustomObject>
    <fields>
        <fullName>Destination__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Destination</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>Change Sets (Inbound)</relationshipLabel>
        <relationshipName>Change_Sets1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Origin</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>Change Sets (Outbound)</relationshipLabel>
        <relationshipName>Change_Sets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Change Set</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Change Sets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Environment__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Organization_ID__c</fullName>
        <label>Organization ID</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Use</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refreshed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>User Acceptance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staging</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Production</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MetaforceChangeListCntrlr.cls
public class MetaforceChangeListCntrlr {
     // PROPERTIES
     public List<MetaforceChangeWrapperCls> chgList {get;set;}
     public Set<String> selChangeNames {get;set;}
     public Boolean hasSelChg {get;set;}
     public String chgSetId {set;get;}
     public String chgSetEnv {set;get;}
     private List<Change_Junction__c> ncj;
     private SObject<Change_Set__c> chgSetPr;

     // CONSTRUCTOR
     public MetaforceChangeListCntrlr(){
          chgList = new List<MetaforceChangeWrapperCls>();
          selChangeNames = new Set<String>();
          chgSetId = apexpages.currentpage().getparameters().get('csId');
          chgSetEnv = apexpages.currentpage().getparameters().get('csEnv');
          ncj = new List<Change_Junction__c>{};
          chgSetPr = [SELECT Id FROM Change_Set__c Where Id = :chgSetId];

          for(Change__c c : [SELECT Id, Name, Type__c, Metadata__c, Name__c, Description__c, Manual_Change__c, Sprint_Number__c, Story_ID__c, CreatedDate 
                                FROM Change__c 
                                WHERE Environment__c = :chgSetEnv AND Id NOT IN (SELECT Change__c 
                                                    FROM Change_Junction__c
                                                    WHERE Change_Set__c  = :chgSetId) 
                                ORDER BY CreatedDate DESC]){
                                    chgList.add(new MetaforceChangeWrapperCls(c));
          }
     }

     // METHODS
     public void displaySelectedChangeNames(){
          selChangeNames.clear();
//          hasSelChg = false;
          for(MetaforceChangeWrapperCls cWrapper : chgList){
               if(cWrapper.isSelected){
//                  hasSelChg = true;
                    selChangeNames.add(cWrapper.cChange.Name__c);
               }
          }
     }
     
     public pageReference createChangeJunctions() {
        selChangeNames.clear();
//        hasSelChg = false;
        // Iterate through the list of changes
        for(MetaforceChangeWrapperCls cWrapper: chgList){
            if(cWrapper.isSelected){
//                hasSelChg = true;
                // build a new change junction record and add to the change junction list
                ncj.add(new Change_Junction__c(
                    Change__c = cWrapper.cChange.Id,
                    Change_Set__c = chgSetId));
            }
        }
        // Insert new change junction records
        insert ncj;
        // Return Id of the originating change set.
        PageReference changeSetPage = new ApexPages.StandardController(chgSetPr).view();
        changeSetPage.setRedirect(true);
        return changeSetPage;
     }
     
    static testMethod void testMetaforceChangeListCntrlr() {
        
        // Setup new origin Environment record
        Environment__c eOrigin = new Environment__c (
            Name = 'Source Org',
            Organization_ID__c = '1239876',
            Status__c = 'In Use',
            Type__c = 'Integration');
            
        insert eOrigin;
        
        // Setup new destination Environment record
        Environment__c eDestination = new Environment__c (
            Name = 'Destination Org',
            Organization_ID__c = '456976',
            Status__c = 'In Use',
            Type__c = 'Production');
            
        insert eDestination;
                    
        // Setup new Change record
        Change__c c = new Change__c (
            Environment__c = eOrigin.Id,
            Metadata__c = 'Object',
            Name__c = 'Change__c',
            Type__c = 'Create');
            
        insert c;
        
        // Setup new Change Set record
        Change_Set__c cs = new Change_Set__c (
            Name = 'Test Change Set',
            Destination__c = eDestination.Id,
            Origin__c = eOrigin.Id);
        
        insert cs;                
        
        // Setup new Change Junction record
        Change_Junction__c cj = new Change_Junction__c (
            Change__c = c.Id,
            Change_Set__c = cs.Id);
        
        insert cj;   
                
        ApexPages.currentPage().getParameters().put('csId', cs.Id);  
        ApexPages.currentPage().getParameters().put('csEnv', eOrigin.Id); 

        //////////////////////////////////////////////////////////////////                  
        MetaforceChangeListCntrlr metaforceChangeListController = new MetaforceChangeListCntrlr();
        
        metaforceChangeListController.displaySelectedChangeNames();
        metaforceChangeListController.createChangeJunctions();
        
        
        //////////////////////////////////////////////////////////////////
        //Test MetaforceChangeWrapperCls class with "isSelected" set to true.
        MetaforceChangeListCntrlr metaforceChangeListWrapperSelected = new MetaforceChangeListCntrlr();
        MetaforceChangeWrapperCls mWrapper = new MetaforceChangeWrapperCls(c);
        mWrapper.isSelected = true;
        metaforceChangeListWrapperSelected.chgList.add(mWrapper);        
                
        metaforceChangeListWrapperSelected.displaySelectedChangeNames();
        metaforceChangeListWrapperSelected.createChangeJunctions();        
        
    }     
}