src/objects/Change__c.object
<CustomObject>
    <fields>
        <fullName>Environment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>Changes</relationshipLabel>
        <relationshipName>Changes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Metadata__c</fullName>
        <label>Metadata</label>
        <picklist>
            <picklistValues>
                <fullName>Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Object</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Page Layout</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Picklist Values</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Profile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Role Hierarchy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trigger</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VF Page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Workflow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Change</label>
    <nameField>
        <displayFormat>MC-{00000}</displayFormat>
        <label>Change Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Changes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Change_Junction__c.object
<CustomObject>
    <fields>
        <fullName>Change_Set__c</fullName>
        <label>Change Set</label>
        <referenceTo>Change_Set__c</referenceTo>
        <relationshipLabel>Changes</relationshipLabel>
        <relationshipName>Change_Junctions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Change__c</fullName>
        <label>Change</label>
        <referenceTo>Change__c</referenceTo>
        <relationshipLabel>Change Sets</relationshipLabel>
        <relationshipName>Change_Junctions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Change Junction</label>
    <nameField>
        <displayFormat>MCJ-{00000}</displayFormat>
        <label>Change Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Change_Set__c.object
<CustomObject>
    <label>Change Set</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Change Sets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Environment__c.object
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MyChangeListCntrlr.cls
public class MyChangeListCntrlr {
     // PROPERTIES
     public List<ChangeWrapperCls> chgList {get;set;}
     public Set<String> selChangeNames {get;set;}
     public Boolean hasSelChg {get;set;}
     public String chgSetId {set;get;}
     public String chgSetEnv {set;get;}
     private List<Change_Junction__c> ncj;
     private SObject<Change_Set__c> chgSetPr;

     // CONSTRUCTOR
     public MyChangeListCntrlr(){
          chgList = new List<ChangeWrapperCls>();
          selChangeNames = new Set<String>();
          chgSetId = apexpages.currentpage().getparameters().get('csId');
          chgSetEnv = apexpages.currentpage().getparameters().get('csEnv');
          ncj = new List<Change_Junction__c>{};
          chgSetPr = [SELECT Id FROM Change_Set__c Where Id = :chgSetId];

          for(Change__c c : [SELECT Id, Name__c, CreatedDate, Metadata__c 
                                FROM Change__c 
                                WHERE Environment__c = :chgSetEnv AND Id NOT IN (SELECT Change__c 
                                                    FROM Change_Junction__c
                                                    WHERE Change_Set__c  = :chgSetId) 
                                ORDER BY CreatedDate ASC LIMIT 5]){
                                    chgList.add(new ChangeWrapperCls(c));
          }
     }

     // METHODS
     public void displaySelectedChangeNames(){
          selChangeNames.clear();
          hasSelChg = false;
          for(ChangeWrapperCls cWrapper : chgList){
               if(cWrapper.isSelected){
                    hasSelChg = true;
                    selChangeNames.add(cWrapper.cChange.Name__c);
               }
          }
     }
     
     public pageReference createChangeJunctions() {
        selChangeNames.clear();
        hasSelChg = false;
        // Iterate through the list of changes
        for(ChangeWrapperCls cWrapper: chgList){
            if(cWrapper.isSelected){
                hasSelChg = true;
                // build a new change junction record and add to the change junction list
                ncj.add(new Change_Junction__c(
                    Change__c = cWrapper.cChange.Id,
                    Change_Set__c = chgSetId));
            }
        }
        // Insert new change junction records
        insert ncj;
        // Return Id of the originating change set.
        PageReference changeSetPage = new ApexPages.StandardController(chgSetPr).view();
        changeSetPage.setRedirect(true);
        return changeSetPage;
     }
}